version: '3'
services:
  hbase:
    build: hbase/
    hostname: hbase

  hdfs:
    build: hdfs/
    hostname: hdfs
    ports:
    - "9870"
    volumes:
    - hdfs:/opt/hadoop

  hive:
    build: hive/
    hostname: hive
    depends_on:
    - hdfs
    volumes:
    - hdfs:/opt/hadoop:ro
    command: ["--hiveconf", "hive.server2.transport.mode=http"]

  ldap:
    build: knox/
    hostname: ldap
    entrypoint: /ldap.sh

  knox:
    build: knox/
    hostname: knox
    entrypoint: /gateway.sh
    depends_on:
    - ldap
    ports:
    - "8443"

  jmeter-hdfs:
    build: jmeter/
    command: hdfs

  jmeter-hbase:
    build: jmeter/
    command: hbase

volumes:
  hdfs:
