version: '3'
services:
  hbase:
    build: hbase/
    hostname: hbase

  hdfs:
    build: hdfs/
    hostname: hdfs
    ports:
    - "9870"

  hive:
    build: hive/
    hostname: hive

  ldap:
    build: knox/
    hostname: ldap
    entrypoint: /ldap.sh

  knox:
    build: knox/
    hostname: knox
    entrypoint: /gateway.sh
    depends_on:
    - ldap
    ports:
    - "8443"

  jmeter:
    build: jmeter/
    hostname: jmeter

