version: '3'
services:
  hbase:
    build: hbase/
    hostname: hbase
    volumes:
    - hbase:/opt/hbase


  hdfs:
    build: hdfs/
    hostname: hdfs
    volumes:
    - hdfs:/opt/hadoop

  hive:
    build: hive/
    hostname: hive
    depends_on:
    - hdfs
    volumes:
    - hdfs:/opt/hadoop:ro
    - hive:/opt/hive
    command: ["--hiveconf", "hive.server2.transport.mode=http", "--hiveconf", "hive.server2.thrift.resultset.max.fetch.size=100000"]

  hive-binary:
    build: hive/
    hostname: hive-binary
    depends_on:
    - hdfs
    volumes:
    - hdfs:/opt/hadoop:ro
    command: ["--hiveconf", "hive.server2.transport.mode=binary", "--hiveconf", "hive.server2.thrift.resultset.max.fetch.size=100000"]

  ldap:
    build: knox/
    hostname: ldap
    entrypoint: /ldap.sh

  knox:
    build: knox/
    hostname: knox
    entrypoint: /gateway.sh
    depends_on:
    - ldap
    ports:
    - "8443"

  jmeter-hdfs:
    build: jmeter/
    command: hdfs
    depends_on:
    - hdfs
    - knox

  jmeter-hbase:
    build: jmeter/
    command: hbase
    depends_on:
    - hbase
    - knox

  jmeter-hive:
    build: jmeter/
    command: hive
    depends_on:
    - hive
    - knox
    volumes:
    - hive:/opt/hive:ro

  test-hbase:
    image: busybox
    depends_on:
    - hbase
    - knox

  test-hdfs:
    build: test-hdfs/
    depends_on:
    - hdfs
    - knox
    volumes:
    - hdfs:/opt/hadoop:ro

  test-hbase:
    build: test-hbase/
    depends_on:
    - hbase
    - knox
    volumes:
    - hbase:/opt/hbase:ro

  test-hive:
    build: test-hive/
    depends_on:
    - hive
    - knox
    volumes:
    - hdfs:/opt/hadoop:ro
    - hive:/opt/hive:ro

volumes:
  hbase:
  hdfs:
  hive:
